<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PrincipalSearchController extends Controller
{
    public function index()
    {
        
    }

    public function search(Request $request)
	{
		if($request->ajax())
		{
			$output="";
			
			$college_topics = DB::table('colleges')->join('college_topics', 'colleges.id', '=', 'college_topics.college_id')->where('college_topics.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('college_topics.deleted_at', '=', null);})->orderBy('college_topics.name', 'asc')->get();
            $college_sections = DB::table('colleges')->join('college_topics', 'colleges.id', '=', 'college_topics.college_id')->join('college_topic_sections', 'college_topics.id', '=', 'college_topic_sections.college_topic_id')->where('college_topic_sections.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('college_topic_sections.deleted_at', '=', null);})->orderBy('college_topic_sections.name', 'asc')->get();
            $college_files = DB::table('colleges')->join('college_topics', 'colleges.id', '=', 'college_topics.college_id')->join('college_topic_sections', 'college_topics.id', '=', 'college_topic_sections.college_topic_id')->join('college_t_s_files', 'college_topic_sections.id', '=', 'college_t_s_files.college_topic_section_id')->where('college_t_s_files.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('college_t_s_files.deleted_at', '=', null);})->orderBy('college_t_s_files.name', 'asc')->get();
			$college_notes = DB::table('colleges')->join('college_topics', 'colleges.id', '=', 'college_topics.college_id')->join('college_topic_sections', 'college_topics.id', '=', 'college_topic_sections.college_topic_id')->join('college_t_s_notes', 'college_topic_sections.id', '=', 'college_t_s_notes.college_topic_section_id')->where('college_t_s_notes.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('college_t_s_notes.deleted_at', '=', null);})->orderBy('college_t_s_notes.name', 'asc')->get();
			$college_galeries = DB::table('colleges')->join('college_topics', 'colleges.id', '=', 'college_topics.college_id')->join('college_topic_sections', 'college_topics.id', '=', 'college_topic_sections.college_topic_id')->join('college_t_s_galeries', 'college_topic_sections.id', '=', 'college_t_s_galeries.college_topic_section_id')->where('college_t_s_galeries.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('college_t_s_galeries.deleted_at', '=', null);})->orderBy('college_t_s_galeries.name', 'asc')->get();
			$college_playlists = DB::table('colleges')->join('college_topics', 'colleges.id', '=', 'college_topics.college_id')->join('college_topic_sections', 'college_topics.id', '=', 'college_topic_sections.college_topic_id')->join('college_t_s_playlists', 'college_topic_sections.id', '=', 'college_t_s_playlists.c_t_s_id')->where('college_t_s_playlists.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('college_t_s_playlists.deleted_at', '=', null);})->orderBy('college_t_s_playlists.name', 'asc')->get();
			$college_tools = DB::table('colleges')->join('college_topics', 'colleges.id', '=', 'college_topics.college_id')->join('college_topic_sections', 'college_topics.id', '=', 'college_topic_sections.college_topic_id')->join('college_t_s_tools', 'college_topic_sections.id', '=', 'college_t_s_tools.college_topic_section_id')->where('college_t_s_tools.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('college_t_s_tools.deleted_at', '=', null);})->orderBy('college_t_s_tools.name', 'asc')->get();
 
            $job_topics = DB::table('jobs')->join('job_topics', 'jobs.id', '=', 'job_topics.job_id')->where('job_topics.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('job_topics.deleted_at', '=', null);})->orderBy('job_topics.name', 'asc')->get();
            $job_sections = DB::table('jobs')->join('job_topics', 'jobs.id', '=', 'job_topics.job_id')->join('job_topic_sections', 'job_topics.id', '=', 'job_topic_sections.job_topic_id')->where('job_topic_sections.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('job_topic_sections.deleted_at', '=', null);})->orderBy('job_topic_sections.name', 'asc')->get();
            $job_files = DB::table('jobs')->join('job_topics', 'jobs.id', '=', 'job_topics.job_id')->join('job_topic_sections', 'job_topics.id', '=', 'job_topic_sections.job_topic_id')->join('job_t_s_files', 'job_topic_sections.id', '=', 'job_t_s_files.job_topic_section_id')->where('job_t_s_files.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('job_t_s_files.deleted_at', '=', null);})->orderBy('job_t_s_files.name', 'asc')->get();
			$job_notes = DB::table('jobs')->join('job_topics', 'jobs.id', '=', 'job_topics.job_id')->join('job_topic_sections', 'job_topics.id', '=', 'job_topic_sections.job_topic_id')->join('job_t_s_notes', 'job_topic_sections.id', '=', 'job_t_s_notes.job_topic_section_id')->where('job_t_s_notes.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('job_t_s_notes.deleted_at', '=', null);})->orderBy('job_t_s_notes.name', 'asc')->get();
			$job_galeries = DB::table('jobs')->join('job_topics', 'jobs.id', '=', 'job_topics.job_id')->join('job_topic_sections', 'job_topics.id', '=', 'job_topic_sections.job_topic_id')->join('job_t_s_galeries', 'job_topic_sections.id', '=', 'job_t_s_galeries.job_topic_section_id')->where('job_t_s_galeries.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('job_t_s_galeries.deleted_at', '=', null);})->orderBy('job_t_s_galeries.name', 'asc')->get();
			$job_playlists = DB::table('jobs')->join('job_topics', 'jobs.id', '=', 'job_topics.job_id')->join('job_topic_sections', 'job_topics.id', '=', 'job_topic_sections.job_topic_id')->join('job_t_s_playlists', 'job_topic_sections.id', '=', 'job_t_s_playlists.c_t_s_id')->where('job_t_s_playlists.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('job_t_s_playlists.deleted_at', '=', null);})->orderBy('job_t_s_playlists.name', 'asc')->get();
			$job_tools = DB::table('jobs')->join('job_topics', 'jobs.id', '=', 'job_topics.job_id')->join('job_topic_sections', 'job_topics.id', '=', 'job_topic_sections.job_topic_id')->join('job_t_s_tools', 'job_topic_sections.id', '=', 'job_t_s_tools.job_topic_section_id')->where('job_t_s_tools.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('job_t_s_tools.deleted_at', '=', null);})->orderBy('job_t_s_tools.name', 'asc')->get();

            $project_topics = DB::table('projects')->join('project_topics', 'projects.id', '=', 'project_topics.project_id')->where('project_topics.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('project_topics.deleted_at', '=', null);})->orderBy('project_topics.name', 'asc')->get();
            $project_sections = DB::table('projects')->join('project_topics', 'projects.id', '=', 'project_topics.project_id')->join('project_topic_sections', 'project_topics.id', '=', 'project_topic_sections.project_topic_id')->where('project_topic_sections.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('project_topic_sections.deleted_at', '=', null);})->orderBy('project_topic_sections.name', 'asc')->get();
            $project_files = DB::table('projects')->join('project_topics', 'projects.id', '=', 'project_topics.project_id')->join('project_topic_sections', 'project_topics.id', '=', 'project_topic_sections.project_topic_id')->join('project_t_s_files', 'project_topic_sections.id', '=', 'project_t_s_files.project_topic_section_id')->where('project_t_s_files.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('project_t_s_files.deleted_at', '=', null);})->orderBy('project_t_s_files.name', 'asc')->get();
			$project_notes = DB::table('projects')->join('project_topics', 'projects.id', '=', 'project_topics.project_id')->join('project_topic_sections', 'project_topics.id', '=', 'project_topic_sections.project_topic_id')->join('project_t_s_notes', 'project_topic_sections.id', '=', 'project_t_s_notes.project_topic_section_id')->where('project_t_s_notes.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('project_t_s_notes.deleted_at', '=', null);})->orderBy('project_t_s_notes.name', 'asc')->get();
			$project_galeries = DB::table('projects')->join('project_topics', 'projects.id', '=', 'project_topics.project_id')->join('project_topic_sections', 'project_topics.id', '=', 'project_topic_sections.project_topic_id')->join('project_t_s_galeries', 'project_topic_sections.id', '=', 'project_t_s_galeries.project_topic_section_id')->where('project_t_s_galeries.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('project_t_s_galeries.deleted_at', '=', null);})->orderBy('project_t_s_galeries.name', 'asc')->get();
			$project_playlists = DB::table('projects')->join('project_topics', 'projects.id', '=', 'project_topics.project_id')->join('project_topic_sections', 'project_topics.id', '=', 'project_topic_sections.project_topic_id')->join('project_t_s_playlists', 'project_topic_sections.id', '=', 'project_t_s_playlists.c_t_s_id')->where('project_t_s_playlists.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('project_t_s_playlists.deleted_at', '=', null);})->orderBy('project_t_s_playlists.name', 'asc')->get();
			$project_tools = DB::table('projects')->join('project_topics', 'projects.id', '=', 'project_topics.project_id')->join('project_topic_sections', 'project_topics.id', '=', 'project_topic_sections.project_topic_id')->join('project_t_s_tools', 'project_topic_sections.id', '=', 'project_t_s_tools.project_topic_section_id')->where('project_t_s_tools.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('project_t_s_tools.deleted_at', '=', null);})->orderBy('project_t_s_tools.name', 'asc')->get();
 
            $personal_data_topics = DB::table('personal_datas')->join('personal_data_topics', 'personal_datas.id', '=', 'personal_data_topics.personal_data_id')->where('personal_data_topics.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('personal_data_topics.deleted_at', '=', null);})->orderBy('personal_data_topics.name', 'asc')->get();
            $personal_data_sections = DB::table('personal_datas')->join('personal_data_topics', 'personal_datas.id', '=', 'personal_data_topics.personal_data_id')->join('personal_data_topic_sections', 'personal_data_topics.id', '=', 'personal_data_topic_sections.personal_data_topic_id')->where('personal_data_topic_sections.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('personal_data_topic_sections.deleted_at', '=', null);})->orderBy('personal_data_topic_sections.name', 'asc')->get();
            $personal_data_files = DB::table('personal_datas')->join('personal_data_topics', 'personal_datas.id', '=', 'personal_data_topics.personal_data_id')->join('personal_data_topic_sections', 'personal_data_topics.id', '=', 'personal_data_topic_sections.personal_data_topic_id')->join('personal_data_t_s_files', 'personal_data_topic_sections.id', '=', 'personal_data_t_s_files.personal_data_t_s_id')->where('personal_data_t_s_files.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('personal_data_t_s_files.deleted_at', '=', null);})->orderBy('personal_data_t_s_files.name', 'asc')->get();
            $personal_data_notes = DB::table('personal_datas')->join('personal_data_topics', 'personal_datas.id', '=', 'personal_data_topics.personal_data_id')->join('personal_data_topic_sections', 'personal_data_topics.id', '=', 'personal_data_topic_sections.personal_data_topic_id')->join('personal_data_t_s_notes', 'personal_data_topic_sections.id', '=', 'personal_data_t_s_notes.personal_data_t_s_id')->where('personal_data_t_s_notes.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('personal_data_t_s_notes.deleted_at', '=', null);})->orderBy('personal_data_t_s_notes.name', 'asc')->get();
            $personal_data_galeries = DB::table('personal_datas')->join('personal_data_topics', 'personal_datas.id', '=', 'personal_data_topics.personal_data_id')->join('personal_data_topic_sections', 'personal_data_topics.id', '=', 'personal_data_topic_sections.personal_data_topic_id')->join('personal_data_t_s_galeries', 'personal_data_topic_sections.id', '=', 'personal_data_t_s_galeries.personal_data_t_s_id')->where('personal_data_t_s_galeries.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('personal_data_t_s_galeries.deleted_at', '=', null);})->orderBy('personal_data_t_s_galeries.name', 'asc')->get();
            $personal_data_playlists = DB::table('personal_datas')->join('personal_data_topics', 'personal_datas.id', '=', 'personal_data_topics.personal_data_id')->join('personal_data_topic_sections', 'personal_data_topics.id', '=', 'personal_data_topic_sections.personal_data_topic_id')->join('personal_data_t_s_playlists', 'personal_data_topic_sections.id', '=', 'personal_data_t_s_playlists.p_d_t_s_id')->where('personal_data_t_s_playlists.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('personal_data_t_s_playlists.deleted_at', '=', null);})->orderBy('personal_data_t_s_playlists.name', 'asc')->get();
            $personal_data_tools = DB::table('personal_datas')->join('personal_data_topics', 'personal_datas.id', '=', 'personal_data_topics.personal_data_id')->join('personal_data_topic_sections', 'personal_data_topics.id', '=', 'personal_data_topic_sections.personal_data_topic_id')->join('personal_data_t_s_tools', 'personal_data_topic_sections.id', '=', 'personal_data_t_s_tools.personal_data_topic_section_id')->where('personal_data_t_s_tools.name','LIKE','%'.$request->search."%")->where(function ($query) {$query->where('user_id', '=', Auth::user()->id);})->where(function ($query) {$query->where('personal_data_t_s_tools.deleted_at', '=', null);})->orderBy('personal_data_t_s_tools.name', 'asc')->get();
 
            $calendar_events = DB::table('calendar_events')->where('user_id', '=', $user_id)->where('name', 'LIKE', '%'.$request->search."%")->where(function ($query) {$query->where('calendar_events.deleted_at', '=', null);});
            $messages = DB::table('messages')->where('user_id', '=', $user_id)->where('subject', 'LIKE', '%'.$request->search."%")->where(function ($query) {$query->where('messages.deleted_at', '=', null);});
            $contacts = DB::table('contacts')->join('user', 'contacts.contact_id', '=', 'users.id')->where('user_id', '=', $user_id)->where('name', 'LIKE', '%'.$request->search."%")->where(function ($query) {$query->where('contacts.deleted_at', '=', null);});
 
			if($topics)
 			{
				foreach ($topics as $key => $topic)
				{
					$output.='<tr>'.'<td> <a href = "'.route("collegeTopics.show", [ $topic -> id ]).'">'.$topic->name.'</a></td>'.'</tr>';
				}
 
				return Response($output);
 			}
 		}
 	}
}