<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Auth;

class SharedFileController extends Controller
{
    public function index(Request $request)
    {
        if(Auth::user() != null)
        {
            $user_id = Auth::user()->id;
            
            $college_p = $request -> college_p;
            $college_topic_p = $request -> college_topic_p;
            $college_section_p = $request -> college_section_p;
            $college_file_p = $request -> college_file_p;
            $college_note_p = $request -> college_note_p;
            $college_galery_p = $request -> college_galery_p;
            $college_image_p = $request -> college_image_p;
            $college_playlist_p = $request -> college_playlist_p;
            $college_audio_p = $request -> college_audio_p;
            $college_tool_p = $request -> college_tool_p;
            $college_tool_file_p = $request -> college_tool_file_p;
            
            $colleges = DB::table('user_colleges')->join('colleges', 'user_colleges.college_id', '=', 'colleges.id')->join('users', 'user_colleges.user_id', '=', 'users.id')->where('user_colleges.user_id', '=', $user_id)->where(function ($query) {$query->where('user_colleges.deleted_at', '=', null);})->orderBy('user_colleges.created_at', 'desc')->select('colleges.name AS college_name', 'colleges.id AS college_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_colleges.datetime AS datetime')->paginate(50, ['*'], 'college_p');
            $collegeTopics = DB::table('user_college_topics')->join('college_topics', 'user_college_topics.college_topic_id', '=', 'college_topics.id')->join('users', 'user_college_topics.user_id', '=', 'users.id')->where('user_college_topics.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_topics.deleted_at', '=', null);})->orderBy('user_college_topics.created_at', 'desc')->select('college_topics.name AS topic_name', 'college_topics.id AS topic_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_topics.datetime AS datetime')->paginate(50, ['*'], 'college_topic_p');
            $collegeSections = DB::table('user_college_topic_sections')->join('college_topic_sections', 'user_college_topic_sections.college_topic_section_id', '=', 'college_topic_sections.id')->join('users', 'user_college_topic_sections.user_id', '=', 'users.id')->where('user_college_topic_sections.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_topic_sections.deleted_at', '=', null);})->orderBy('user_college_topic_sections.created_at', 'desc')->select('college_topic_sections.name AS section_name', 'college_topic_sections.id AS section_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_topic_sections.datetime AS datetime')->paginate(50, ['*'], 'college_section__p');
            $collegeFiles = DB::table('user_college_t_s_files')->join('college_t_s_files', 'user_college_t_s_files.college_t_s_file_id', '=', 'college_t_s_files.id')->join('users', 'user_college_t_s_files.user_id', '=', 'users.id')->where('user_college_t_s_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_files.deleted_at', '=', null);})->orderBy('user_college_t_s_files.created_at', 'desc')->select('college_t_s_files.name AS file_name', 'college_t_s_files.id AS file_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_files.datetime AS datetime')->paginate(50, ['*'], 'college_file_p');
            $collegeNotes = DB::table('user_college_t_s_notes')->join('college_t_s_notes', 'user_college_t_s_notes.college_t_s_note_id', '=', 'college_t_s_notes.id')->join('users', 'user_college_t_s_notes.user_id', '=', 'users.id')->where('user_college_t_s_notes.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_notes.deleted_at', '=', null);})->orderBy('user_college_t_s_notes.created_at', 'desc')->select('college_t_s_notes.name AS note_name', 'college_t_s_notes.id AS note_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_notes.datetime AS datetime')->paginate(50, ['*'], 'college_note_p');
            $collegeGaleries = DB::table('user_college_t_s_galeries')->join('college_t_s_galeries', 'user_college_t_s_galeries.college_t_s_galery_id', '=', 'college_t_s_galeries.id')->join('users', 'user_college_t_s_galeries.user_id', '=', 'users.id')->where('user_college_t_s_galeries.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_galeries.deleted_at', '=', null);})->orderBy('user_college_t_s_galeries.created_at', 'desc')->select('college_t_s_galeries.name AS galery_name', 'college_t_s_galeries.id AS galery_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_galeries.datetime AS datetime')->paginate(50, ['*'], 'college_galery_p');
            $collegeImages = DB::table('user_college_t_s_galery_images')->join('college_t_s_galery_images', 'user_college_t_s_galery_images.college_t_s_g_image_id', '=', 'college_t_s_galery_images.id')->join('users', 'user_college_t_s_galery_images.user_id', '=', 'users.id')->where('user_college_t_s_galery_images.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_galery_images.deleted_at', '=', null);})->orderBy('user_college_t_s_galery_images.created_at', 'desc')->select('college_t_s_galery_images.name AS image_name', 'college_t_s_galery_images.id AS image_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_galery_images.datetime AS datetime')->paginate(50, ['*'], 'college_image_p');
            $collegePlaylists = DB::table('user_college_t_s_playlists')->join('college_t_s_playlists', 'user_college_t_s_playlists.c_t_s_p_id', '=', 'college_t_s_playlists.id')->join('users', 'user_college_t_s_playlists.user_id', '=', 'users.id')->where('user_college_t_s_playlists.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_playlists.deleted_at', '=', null);})->orderBy('user_college_t_s_playlists.created_at', 'desc')->select('college_t_s_playlists.name AS playlist_name', 'college_t_s_playlists.id AS playlist_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_playlists.datetime AS datetime')->paginate(50, ['*'], 'college_playlist_p');
            $collegeAudios = DB::table('user_college_t_s_p_audios')->join('college_t_s_p_audios', 'user_college_t_s_p_audios.c_t_s_p_a_id', '=', 'college_t_s_p_audios.id')->join('users', 'user_college_t_s_p_audios.user_id', '=', 'users.id')->where('user_college_t_s_p_audios.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_p_audios.deleted_at', '=', null);})->orderBy('user_college_t_s_p_audios.created_at', 'desc')->select('college_t_s_p_audios.name AS audio_name', 'college_t_s_p_audios.id AS audio_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_p_audios.datetime AS datetime')->paginate(50, ['*'], 'college_audio_p');
            $collegeTools = DB::table('user_college_t_s_tools')->join('college_t_s_tools', 'user_college_t_s_tools.college_t_s_tool_id', '=', 'college_t_s_tools.id')->join('users', 'user_college_t_s_tools.user_id', '=', 'users.id')->where('user_college_t_s_tools.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_tools.deleted_at', '=', null);})->orderBy('user_college_t_s_tools.created_at', 'desc')->select('college_t_s_tools.name AS tool_name', 'college_t_s_tools.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_tools.datetime AS datetime')->paginate(50, ['*'], 'college_tool_p');
            $collegeToolFiles = DB::table('user_college_t_s_tool_files')->join('college_t_s_tool_files', 'user_college_t_s_tool_files.college_t_s_t_file_id', '=', 'college_t_s_tool_files.id')->join('users', 'user_college_t_s_tool_files.user_id', '=', 'users.id')->where('user_college_t_s_tool_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_tool_files.deleted_at', '=', null);})->orderBy('user_college_t_s_tool_files.created_at', 'desc')->select('college_t_s_tool_files.name AS tool_name', 'college_t_s_tool_files.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_tool_files.datetime AS datetime')->paginate(50, ['*'], 'college_tool_file_p');
            
            $job_p = $request -> job_p;
            $job_topic_p = $request -> job_topic_p;
            $job_section_p = $request -> job_section_p;
            $job_file_p = $request -> job_file_p;
            $job_note_p = $request -> job_note_p;
            $job_galery_p = $request -> job_galery_p;
            $job_image_p = $request -> job_image_p;
            $job_playlist_p = $request -> job_playlist_p;
            $job_audio_p = $request -> job_audio_p;
            $job_tool_p = $request -> job_tool_p;
            $job_tool_file_p = $request -> job_tool_file_p;
            
            $jobs = DB::table('user_jobs')->join('jobs', 'user_jobs.job_id', '=', 'jobs.id')->join('users', 'user_jobs.user_id', '=', 'users.id')->where('user_jobs.user_id', '=', $user_id)->where(function ($query) {$query->where('user_jobs.deleted_at', '=', null);})->orderBy('user_jobs.created_at', 'desc')->select('jobs.name AS job_name', 'jobs.id AS job_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_jobs.datetime AS datetime')->paginate(50, ['*'], 'job_p');
            $jobTopics = DB::table('user_job_topics')->join('job_topics', 'user_job_topics.job_topic_id', '=', 'job_topics.id')->join('users', 'user_job_topics.user_id', '=', 'users.id')->where('user_job_topics.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_topics.deleted_at', '=', null);})->orderBy('user_job_topics.created_at', 'desc')->select('job_topics.name AS topic_name', 'job_topics.id AS topic_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_topics.datetime AS datetime')->paginate(50, ['*'], 'job_topic_p');
            $jobSections = DB::table('user_job_topic_sections')->join('job_topic_sections', 'user_job_topic_sections.job_topic_section_id', '=', 'job_topic_sections.id')->join('users', 'user_job_topic_sections.user_id', '=', 'users.id')->where('user_job_topic_sections.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_topic_sections.deleted_at', '=', null);})->orderBy('user_job_topic_sections.created_at', 'desc')->select('job_topic_sections.name AS section_name', 'job_topic_sections.id AS section_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_topic_sections.datetime AS datetime')->paginate(50, ['*'], 'job_section_p');
            $jobFiles = DB::table('user_job_t_s_files')->join('job_t_s_files', 'user_job_t_s_files.job_t_s_file_id', '=', 'job_t_s_files.id')->join('users', 'user_job_t_s_files.user_id', '=', 'users.id')->where('user_job_t_s_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_files.deleted_at', '=', null);})->orderBy('user_job_t_s_files.created_at', 'desc')->select('job_t_s_files.name AS file_name', 'job_t_s_files.id AS file_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_files.datetime AS datetime')->paginate(50, ['*'], 'job_file_p');
            $jobNotes = DB::table('user_job_t_s_notes')->join('job_t_s_notes', 'user_job_t_s_notes.job_t_s_note_id', '=', 'job_t_s_notes.id')->join('users', 'user_job_t_s_notes.user_id', '=', 'users.id')->where('user_job_t_s_notes.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_notes.deleted_at', '=', null);})->orderBy('user_job_t_s_notes.created_at', 'desc')->select('job_t_s_notes.name AS note_name', 'job_t_s_notes.id AS note_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_notes.datetime AS datetime')->paginate(50, ['*'], 'job_note_p');
            $jobGaleries = DB::table('user_job_t_s_galeries')->join('job_t_s_galeries', 'user_job_t_s_galeries.job_t_s_galery_id', '=', 'job_t_s_galeries.id')->join('users', 'user_job_t_s_galeries.user_id', '=', 'users.id')->where('user_job_t_s_galeries.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_galeries.deleted_at', '=', null);})->orderBy('user_job_t_s_galeries.created_at', 'desc')->select('job_t_s_galeries.name AS galery_name', 'job_t_s_galeries.id AS galery_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_galeries.datetime AS datetime')->paginate(50, ['*'], 'job_galery_p');
            $jobImages = DB::table('user_job_t_s_galery_images')->join('job_t_s_galery_images', 'user_job_t_s_galery_images.job_t_s_g_image_id', '=', 'job_t_s_galery_images.id')->join('users', 'user_job_t_s_galery_images.user_id', '=', 'users.id')->where('user_job_t_s_galery_images.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_galery_images.deleted_at', '=', null);})->orderBy('user_job_t_s_galery_images.created_at', 'desc')->select('job_t_s_galery_images.name AS image_name', 'job_t_s_galery_images.id AS image_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_galery_images.datetime AS datetime')->paginate(50, ['*'], 'job_image_p');
            $jobPlaylists = DB::table('user_job_t_s_playlists')->join('job_t_s_playlists', 'user_job_t_s_playlists.j_t_s_p_id', '=', 'job_t_s_playlists.id')->join('users', 'user_job_t_s_playlists.user_id', '=', 'users.id')->where('user_job_t_s_playlists.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_playlists.deleted_at', '=', null);})->orderBy('user_job_t_s_playlists.created_at', 'desc')->select('job_t_s_playlists.name AS playlist_name', 'job_t_s_playlists.id AS playlist_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_playlists.datetime AS datetime')->paginate(50, ['*'], 'job_playlist_p');
            $jobAudios = DB::table('user_job_t_s_p_audios')->join('job_t_s_p_audios', 'user_job_t_s_p_audios.j_t_s_p_a_id', '=', 'job_t_s_p_audios.id')->join('users', 'user_job_t_s_p_audios.user_id', '=', 'users.id')->where('user_job_t_s_p_audios.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_p_audios.deleted_at', '=', null);})->orderBy('user_job_t_s_p_audios.created_at', 'desc')->select('job_t_s_p_audios.name AS audio_name', 'job_t_s_p_audios.id AS audio_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_p_audios.datetime AS datetime')->paginate(50, ['*'], 'job_audio_p');
            $jobTools = DB::table('user_job_t_s_tools')->join('job_t_s_tools', 'user_job_t_s_tools.job_t_s_tool_id', '=', 'job_t_s_tools.id')->join('users', 'user_job_t_s_tools.user_id', '=', 'users.id')->where('user_job_t_s_tools.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_tools.deleted_at', '=', null);})->orderBy('user_job_t_s_tools.created_at', 'desc')->select('job_t_s_tools.name AS tool_name', 'job_t_s_tools.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_tools.datetime AS datetime')->paginate(50, ['*'], 'job_tool_p');
            $jobToolFiles = DB::table('user_job_t_s_tool_files')->join('job_t_s_tool_files', 'user_job_t_s_tool_files.job_t_s_t_file_id', '=', 'job_t_s_tool_files.id')->join('users', 'user_job_t_s_tool_files.user_id', '=', 'users.id')->where('user_job_t_s_tool_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_tool_files.deleted_at', '=', null);})->orderBy('user_job_t_s_tool_files.created_at', 'desc')->select('job_t_s_tool_files.name AS tool_name', 'job_t_s_tool_files.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_tool_files.datetime AS datetime')->paginate(50, ['*'], 'job_tool_file_p');
    
            $project_p = $request -> project_p;
            $project_topic_p = $request -> project_topic_p;
            $project_section_p = $request -> project_section_p;
            $project_file_p = $request -> project_file_p;
            $project_note_p = $request -> project_note_p;
            $project_galery_p = $request -> project_galery_p;
            $project_image_p = $request -> project_image_p;
            $project_playlist_p = $request -> project_playlist_p;
            $project_audio_p = $request -> project_audio_p;
            $project_tool_p = $request -> project_tool_p;
            $project_tool_file_p = $request -> project_tool_file_p;
    
            $projects = DB::table('user_projects')->join('projects', 'user_projects.project_id', '=', 'projects.id')->join('users', 'user_projects.user_id', '=', 'users.id')->where('user_projects.user_id', '=', $user_id)->where(function ($query) {$query->where('user_projects.deleted_at', '=', null);})->orderBy('user_projects.created_at', 'desc')->select('projects.name AS project_name', 'projects.id AS project_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_projects.datetime AS datetime')->paginate(50, ['*'], 'project_p');
            $projectTopics = DB::table('user_project_topics')->join('project_topics', 'user_project_topics.project_topic_id', '=', 'project_topics.id')->join('users', 'user_project_topics.user_id', '=', 'users.id')->where('user_project_topics.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_topics.deleted_at', '=', null);})->orderBy('user_project_topics.created_at', 'desc')->select('project_topics.name AS topic_name', 'project_topics.id AS topic_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_topics.datetime AS datetime')->paginate(50, ['*'], 'project_topic_p');
            $projectSections = DB::table('user_project_topic_sections')->join('project_topic_sections', 'user_project_topic_sections.project_topic_section_id', '=', 'project_topic_sections.id')->join('users', 'user_project_topic_sections.user_id', '=', 'users.id')->where('user_project_topic_sections.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_topic_sections.deleted_at', '=', null);})->orderBy('user_project_topic_sections.created_at', 'desc')->select('project_topic_sections.name AS section_name', 'project_topic_sections.id AS section_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_topic_sections.datetime AS datetime')->paginate(50, ['*'], 'project_section_p');
            $projectFiles = DB::table('user_project_t_s_files')->join('project_t_s_files', 'user_project_t_s_files.project_t_s_file_id', '=', 'project_t_s_files.id')->join('users', 'user_project_t_s_files.user_id', '=', 'users.id')->where('user_project_t_s_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_files.deleted_at', '=', null);})->orderBy('user_project_t_s_files.created_at', 'desc')->select('project_t_s_files.name AS file_name', 'project_t_s_files.id AS file_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_files.datetime AS datetime')->paginate(50, ['*'], 'project_file_p');
            $projectNotes = DB::table('user_project_t_s_notes')->join('project_t_s_notes', 'user_project_t_s_notes.project_t_s_note_id', '=', 'project_t_s_notes.id')->join('users', 'user_project_t_s_notes.user_id', '=', 'users.id')->where('user_project_t_s_notes.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_notes.deleted_at', '=', null);})->orderBy('user_project_t_s_notes.created_at', 'desc')->select('project_t_s_notes.name AS note_name', 'project_t_s_notes.id AS note_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_notes.datetime AS datetime')->paginate(50, ['*'], 'project_note_p');
            $projectGaleries = DB::table('user_project_t_s_galeries')->join('project_t_s_galeries', 'user_project_t_s_galeries.project_t_s_galery_id', '=', 'project_t_s_galeries.id')->join('users', 'user_project_t_s_galeries.user_id', '=', 'users.id')->where('user_project_t_s_galeries.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_galeries.deleted_at', '=', null);})->orderBy('user_project_t_s_galeries.created_at', 'desc')->select('project_t_s_galeries.name AS galery_name', 'project_t_s_galeries.id AS galery_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_galeries.datetime AS datetime')->paginate(50, ['*'], 'project_galery_p');
            $projectImages = DB::table('user_project_t_s_galery_images')->join('project_t_s_galery_images', 'user_project_t_s_galery_images.project_t_s_g_image_id', '=', 'project_t_s_galery_images.id')->join('users', 'user_project_t_s_galery_images.user_id', '=', 'users.id')->where('user_project_t_s_galery_images.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_galery_images.deleted_at', '=', null);})->orderBy('user_project_t_s_galery_images.created_at', 'desc')->select('project_t_s_galery_images.name AS image_name', 'project_t_s_galery_images.id AS image_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_galery_images.datetime AS datetime')->paginate(50, ['*'], 'project_image_p');
            $projectPlaylists = DB::table('user_project_t_s_playlists')->join('project_t_s_playlists', 'user_project_t_s_playlists.p_t_s_p_id', '=', 'project_t_s_playlists.id')->join('users', 'user_project_t_s_playlists.user_id', '=', 'users.id')->where('user_project_t_s_playlists.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_playlists.deleted_at', '=', null);})->orderBy('user_project_t_s_playlists.created_at', 'desc')->select('project_t_s_playlists.name AS playlist_name', 'project_t_s_playlists.id AS playlist_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_playlists.datetime AS datetime')->paginate(50, ['*'], 'project_playlist_p');
            $projectAudios = DB::table('user_project_t_s_p_audios')->join('project_t_s_p_audios', 'user_project_t_s_p_audios.p_t_s_p_a_id', '=', 'project_t_s_p_audios.id')->join('users', 'user_project_t_s_p_audios.user_id', '=', 'users.id')->where('user_project_t_s_p_audios.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_p_audios.deleted_at', '=', null);})->orderBy('user_project_t_s_p_audios.created_at', 'desc')->select('project_t_s_p_audios.name AS audio_name', 'project_t_s_p_audios.id AS audio_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_p_audios.datetime AS datetime')->paginate(50, ['*'], 'project_audio_p');
            $projectTools = DB::table('user_project_t_s_tools')->join('project_t_s_tools', 'user_project_t_s_tools.project_t_s_tool_id', '=', 'project_t_s_tools.id')->join('users', 'user_project_t_s_tools.user_id', '=', 'users.id')->where('user_project_t_s_tools.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_tools.deleted_at', '=', null);})->orderBy('user_project_t_s_tools.created_at', 'desc')->select('project_t_s_tools.name AS tool_name', 'project_t_s_tools.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_tools.datetime AS datetime')->paginate(50, ['*'], 'project_tool_p');
            $projectToolFiles = DB::table('user_project_t_s_tool_files')->join('project_t_s_tool_files', 'user_project_t_s_tool_files.project_t_s_t_file_id', '=', 'project_t_s_tool_files.id')->join('users', 'user_project_t_s_tool_files.user_id', '=', 'users.id')->where('user_project_t_s_tool_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_tool_files.deleted_at', '=', null);})->orderBy('user_project_t_s_tool_files.created_at', 'desc')->select('project_t_s_tool_files.name AS tool_name', 'project_t_s_tool_files.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_tool_files.datetime AS datetime')->paginate(50, ['*'], 'project_tool_file_p');
    
            $personal_data_p = $request -> personal_data_p;
            $personal_data_topic_p = $request -> personal_data_topic_p;
            $personal_data_section_p = $request -> personal_data_section_p;
            $personal_data_file_p = $request -> personal_data_file_p;
            $personal_data_note_p = $request -> personal_data_note_p;
            $personal_data_galery_p = $request -> personal_data_galery_p;
            $personal_data_image_p = $request -> personal_data_image_p;
            $personal_data_playlist_p = $request -> personal_data_playlist_p;
            $personal_data_audio_p = $request -> personal_data_audio_p;
            $personal_data_tool_p = $request -> personal_data_tool_p;
            $personal_data_tool_file_p = $request -> personal_data_tool_file_p;
    
            $personalDatas = DB::table('user_personal_datas')->join('personal_datas', 'user_personal_datas.personal_data_id', '=', 'personal_datas.id')->join('users', 'user_personal_datas.user_id', '=', 'users.id')->where('user_personal_datas.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_datas.deleted_at', '=', null);})->orderBy('user_personal_datas.created_at', 'desc')->select('personal_datas.name AS personal_data_name', 'personal_datas.id AS personal_data_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_datas.datetime AS datetime')->paginate(50, ['*'], 'personal_data_p');
            $personalDataTopics = DB::table('user_personal_data_topics')->join('personal_data_topics', 'user_personal_data_topics.personal_data_topic_id', '=', 'personal_data_topics.id')->join('users', 'user_personal_data_topics.user_id', '=', 'users.id')->where('user_personal_data_topics.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_topics.deleted_at', '=', null);})->orderBy('user_personal_data_topics.created_at', 'desc')->select('personal_data_topics.name AS topic_name', 'personal_data_topics.id AS topic_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_topics.datetime AS datetime')->paginate(50, ['*'], 'personal_data_topic_p');
            $personalDataSections = DB::table('user_personal_data_topic_sections')->join('personal_data_topic_sections', 'user_personal_data_topic_sections.personal_data_t_s_id', '=', 'personal_data_topic_sections.id')->join('users', 'user_personal_data_topic_sections.user_id', '=', 'users.id')->where('user_personal_data_topic_sections.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_topic_sections.deleted_at', '=', null);})->orderBy('user_personal_data_topic_sections.created_at', 'desc')->select('personal_data_topic_sections.name AS section_name', 'personal_data_topic_sections.id AS section_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_topic_sections.datetime AS datetime')->paginate(50, ['*'], 'personal_data_section_p');
            $personalDataFiles = DB::table('user_personal_data_t_s_files')->join('personal_data_t_s_files', 'user_personal_data_t_s_files.personal_data_t_s_file_id', '=', 'personal_data_t_s_files.id')->join('users', 'user_personal_data_t_s_files.user_id', '=', 'users.id')->where('user_personal_data_t_s_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_files.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_files.created_at', 'desc')->select('personal_data_t_s_files.name AS file_name', 'personal_data_t_s_files.id AS file_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_files.datetime AS datetime')->paginate(50, ['*'], 'personal_data_file_p');
            $personalDataNotes = DB::table('user_personal_data_t_s_notes')->join('personal_data_t_s_notes', 'user_personal_data_t_s_notes.personal_data_t_s_note_id', '=', 'personal_data_t_s_notes.id')->join('users', 'user_personal_data_t_s_notes.user_id', '=', 'users.id')->where('user_personal_data_t_s_notes.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_notes.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_notes.created_at', 'desc')->select('personal_data_t_s_notes.name AS note_name', 'personal_data_t_s_notes.id AS note_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_notes.datetime AS datetime')->paginate(50, ['*'], 'personal_data_note_p');
            $personalDataGaleries = DB::table('user_personal_data_t_s_galeries')->join('personal_data_t_s_galeries', 'user_personal_data_t_s_galeries.personal_data_t_s_g_id', '=', 'personal_data_t_s_galeries.id')->join('users', 'user_personal_data_t_s_galeries.user_id', '=', 'users.id')->where('user_personal_data_t_s_galeries.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_galeries.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_galeries.created_at', 'desc')->select('personal_data_t_s_galeries.name AS galery_name', 'personal_data_t_s_galeries.id AS galery_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_galeries.datetime AS datetime')->paginate(50, ['*'], 'personal_data_galery_p');
            $personalDataImages = DB::table('user_personal_data_t_s_galery_images')->join('personal_data_t_s_galery_images', 'user_personal_data_t_s_galery_images.p_d_t_s_g_i_id', '=', 'personal_data_t_s_galery_images.id')->join('users', 'user_personal_data_t_s_galery_images.user_id', '=', 'users.id')->where('user_personal_data_t_s_galery_images.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_galery_images.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_galery_images.created_at', 'desc')->select('personal_data_t_s_galery_images.name AS image_name', 'personal_data_t_s_galery_images.id AS image_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_galery_images.datetime AS datetime')->paginate(50, ['*'], 'personal_data_image_p');
            $personalDataPlaylists = DB::table('user_personal_data_t_s_p')->join('personal_data_t_s_playlists', 'user_personal_data_t_s_p.p_d_t_s_p_id', '=', 'personal_data_t_s_playlists.id')->join('users', 'user_personal_data_t_s_p.user_id', '=', 'users.id')->where('user_personal_data_t_s_p.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_p.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_p.created_at', 'desc')->select('personal_data_t_s_playlists.name AS playlist_name', 'personal_data_t_s_playlists.id AS playlist_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_p.datetime AS datetime')->paginate(50, ['*'], 'personal_data_playlist_p');
            $personalDataAudios = DB::table('user_p_d_t_s_p_audios')->join('personal_data_t_s_p_audios', 'user_p_d_t_s_p_audios.p_d_t_s_p_a_id', '=', 'personal_data_t_s_p_audios.id')->join('users', 'user_p_d_t_s_p_audios.user_id', '=', 'users.id')->where('user_p_d_t_s_p_audios.user_id', '=', $user_id)->where(function ($query) {$query->where('user_p_d_t_s_p_audios.deleted_at', '=', null);})->orderBy('user_p_d_t_s_p_audios.created_at', 'desc')->select('personal_data_t_s_p_audios.name AS audio_name', 'personal_data_t_s_p_audios.id AS audio_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_p_d_t_s_p_audios.datetime AS datetime')->paginate(50, ['*'], 'personal_data_audio_p');
            $personalDataTools = DB::table('user_personal_data_t_s_tools')->join('personal_data_t_s_tools', 'user_personal_data_t_s_tools.personal_data_t_s_tool_id', '=', 'personal_data_t_s_tools.id')->join('users', 'user_personal_data_t_s_tools.user_id', '=', 'users.id')->where('user_personal_data_t_s_tools.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_tools.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_tools.created_at', 'desc')->select('personal_data_t_s_tools.name AS tool_name', 'personal_data_t_s_tools.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_tools.datetime AS datetime')->paginate(50, ['*'], 'personal_data_tool_p');
            $personalDataToolFiles = DB::table('user_personal_data_t_s_tool_files')->join('personal_data_t_s_tool_files', 'user_personal_data_t_s_tool_files.personal_d_t_s_t_f_id', '=', 'personal_data_t_s_tool_files.id')->join('users', 'user_personal_data_t_s_tool_files.user_id', '=', 'users.id')->where('user_personal_data_t_s_tool_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_tool_files.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_tool_files.created_at', 'desc')->select('personal_data_t_s_tool_files.name AS tool_name', 'personal_data_t_s_tool_files.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_tool_files.datetime AS datetime')->paginate(50, ['*'], 'personal_data_tool_file_p');

            $calendarEvents = DB::table('user_calendar_events')->join('calendar_events', 'user_calendar_events.calendar_event_id', '=', 'calendar_events.id')->join('users', 'calendar_events.user_id', '=', 'users.id')->where('user_calendar_events.user_id', '=', $user_id)->where(function ($query) {$query->where('user_calendar_events.deleted_at', '=', null);})->orderBy('user_calendar_events.created_at', 'desc')->select('calendar_events.name AS calendar_event_name', 'calendar_events.id AS calendar_event_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_calendar_events.datetime AS datetime')->paginate(50, ['*'], 'calendar_event_p');

            $collegesList = DB::table('user_colleges')->join('colleges', 'user_colleges.college_id', '=', 'colleges.id')->join('users', 'user_colleges.user_id', '=', 'users.id')->where('user_colleges.user_id', '=', $user_id)->where(function ($query) {$query->where('user_colleges.deleted_at', '=', null);})->orderBy('user_colleges.created_at', 'desc')->select('colleges.name AS college_name', 'colleges.id AS college_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_colleges.datetime AS datetime')->limit(5)->get();
            $collegeTopicsList = DB::table('user_college_topics')->join('college_topics', 'user_college_topics.college_topic_id', '=', 'college_topics.id')->join('users', 'user_college_topics.user_id', '=', 'users.id')->where('user_college_topics.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_topics.deleted_at', '=', null);})->orderBy('user_college_topics.created_at', 'desc')->select('college_topics.name AS topic_name', 'college_topics.id AS topic_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_topics.datetime AS datetime')->limit(5)->get();
            $collegeSectionsList = DB::table('user_college_topic_sections')->join('college_topic_sections', 'user_college_topic_sections.college_topic_section_id', '=', 'college_topic_sections.id')->join('users', 'user_college_topic_sections.user_id', '=', 'users.id')->where('user_college_topic_sections.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_topic_sections.deleted_at', '=', null);})->orderBy('user_college_topic_sections.created_at', 'desc')->select('college_topic_sections.name AS section_name', 'college_topic_sections.id AS section_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_topic_sections.datetime AS datetime')->limit(5)->get();
            $collegeFilesList = DB::table('user_college_t_s_files')->join('college_t_s_files', 'user_college_t_s_files.college_t_s_file_id', '=', 'college_t_s_files.id')->join('users', 'user_college_t_s_files.user_id', '=', 'users.id')->where('user_college_t_s_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_files.deleted_at', '=', null);})->orderBy('user_college_t_s_files.created_at', 'desc')->select('college_t_s_files.name AS file_name', 'college_t_s_files.id AS file_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_files.datetime AS datetime')->limit(5)->get();
            $collegeNotesList = DB::table('user_college_t_s_notes')->join('college_t_s_notes', 'user_college_t_s_notes.college_t_s_note_id', '=', 'college_t_s_notes.id')->join('users', 'user_college_t_s_notes.user_id', '=', 'users.id')->where('user_college_t_s_notes.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_notes.deleted_at', '=', null);})->orderBy('user_college_t_s_notes.created_at', 'desc')->select('college_t_s_notes.name AS note_name', 'college_t_s_notes.id AS note_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_notes.datetime AS datetime')->limit(5)->get();
            $collegeGaleriesList = DB::table('user_college_t_s_galeries')->join('college_t_s_galeries', 'user_college_t_s_galeries.college_t_s_galery_id', '=', 'college_t_s_galeries.id')->join('users', 'user_college_t_s_galeries.user_id', '=', 'users.id')->where('user_college_t_s_galeries.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_galeries.deleted_at', '=', null);})->orderBy('user_college_t_s_galeries.created_at', 'desc')->select('college_t_s_galeries.name AS galery_name', 'college_t_s_galeries.id AS galery_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_galeries.datetime AS datetime')->limit(5)->get();
            $collegeImagesList = DB::table('user_college_t_s_galery_images')->join('college_t_s_galery_images', 'user_college_t_s_galery_images.college_t_s_g_image_id', '=', 'college_t_s_galery_images.id')->join('users', 'user_college_t_s_galery_images.user_id', '=', 'users.id')->where('user_college_t_s_galery_images.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_galery_images.deleted_at', '=', null);})->orderBy('user_college_t_s_galery_images.created_at', 'desc')->select('college_t_s_galery_images.name AS image_name', 'college_t_s_galery_images.id AS image_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_galery_images.datetime AS datetime')->limit(5)->get();
            $collegePlaylistsList = DB::table('user_college_t_s_playlists')->join('college_t_s_playlists', 'user_college_t_s_playlists.c_t_s_p_id', '=', 'college_t_s_playlists.id')->join('users', 'user_college_t_s_playlists.user_id', '=', 'users.id')->where('user_college_t_s_playlists.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_playlists.deleted_at', '=', null);})->orderBy('user_college_t_s_playlists.created_at', 'desc')->select('college_t_s_playlists.name AS playlist_name', 'college_t_s_playlists.id AS playlist_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_playlists.datetime AS datetime')->limit(5)->get();
            $collegeAudiosList = DB::table('user_college_t_s_p_audios')->join('college_t_s_p_audios', 'user_college_t_s_p_audios.c_t_s_p_a_id', '=', 'college_t_s_p_audios.id')->join('users', 'user_college_t_s_p_audios.user_id', '=', 'users.id')->where('user_college_t_s_p_audios.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_p_audios.deleted_at', '=', null);})->orderBy('user_college_t_s_p_audios.created_at', 'desc')->select('college_t_s_p_audios.name AS audio_name', 'college_t_s_p_audios.id AS audio_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_p_audios.datetime AS datetime')->limit(5)->get();
            $collegeToolsList = DB::table('user_college_t_s_tools')->join('college_t_s_tools', 'user_college_t_s_tools.college_t_s_tool_id', '=', 'college_t_s_tools.id')->join('users', 'user_college_t_s_tools.user_id', '=', 'users.id')->where('user_college_t_s_tools.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_tools.deleted_at', '=', null);})->orderBy('user_college_t_s_tools.created_at', 'desc')->select('college_t_s_tools.name AS tool_name', 'college_t_s_tools.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_tools.datetime AS datetime')->limit(5)->get();
            $collegeToolFilesList = DB::table('user_college_t_s_tool_files')->join('college_t_s_tool_files', 'user_college_t_s_tool_files.college_t_s_t_file_id', '=', 'college_t_s_tool_files.id')->join('users', 'user_college_t_s_tool_files.user_id', '=', 'users.id')->where('user_college_t_s_tool_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_college_t_s_tool_files.deleted_at', '=', null);})->orderBy('user_college_t_s_tool_files.created_at', 'desc')->select('college_t_s_tool_files.name AS tool_name', 'college_t_s_tool_files.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_college_t_s_tool_files.datetime AS datetime')->limit(5)->get();
            
            $jobsList = DB::table('user_jobs')->join('jobs', 'user_jobs.job_id', '=', 'jobs.id')->join('users', 'user_jobs.user_id', '=', 'users.id')->where('user_jobs.user_id', '=', $user_id)->where(function ($query) {$query->where('user_jobs.deleted_at', '=', null);})->orderBy('user_jobs.created_at', 'desc')->select('jobs.name AS job_name', 'jobs.id AS job_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_jobs.datetime AS datetime')->limit(5)->get();
            $jobTopicsList = DB::table('user_job_topics')->join('job_topics', 'user_job_topics.job_topic_id', '=', 'job_topics.id')->join('users', 'user_job_topics.user_id', '=', 'users.id')->where('user_job_topics.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_topics.deleted_at', '=', null);})->orderBy('user_job_topics.created_at', 'desc')->select('job_topics.name AS topic_name', 'job_topics.id AS topic_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_topics.datetime AS datetime')->limit(5)->get();
            $jobSectionsList = DB::table('user_job_topic_sections')->join('job_topic_sections', 'user_job_topic_sections.job_topic_section_id', '=', 'job_topic_sections.id')->join('users', 'user_job_topic_sections.user_id', '=', 'users.id')->where('user_job_topic_sections.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_topic_sections.deleted_at', '=', null);})->orderBy('user_job_topic_sections.created_at', 'desc')->select('job_topic_sections.name AS section_name', 'job_topic_sections.id AS section_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_topic_sections.datetime AS datetime')->limit(5)->get();
            $jobFilesList = DB::table('user_job_t_s_files')->join('job_t_s_files', 'user_job_t_s_files.job_t_s_file_id', '=', 'job_t_s_files.id')->join('users', 'user_job_t_s_files.user_id', '=', 'users.id')->where('user_job_t_s_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_files.deleted_at', '=', null);})->orderBy('user_job_t_s_files.created_at', 'desc')->select('job_t_s_files.name AS file_name', 'job_t_s_files.id AS file_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_files.datetime AS datetime')->limit(5)->get();
            $jobNotesList = DB::table('user_job_t_s_notes')->join('job_t_s_notes', 'user_job_t_s_notes.job_t_s_note_id', '=', 'job_t_s_notes.id')->join('users', 'user_job_t_s_notes.user_id', '=', 'users.id')->where('user_job_t_s_notes.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_notes.deleted_at', '=', null);})->orderBy('user_job_t_s_notes.created_at', 'desc')->select('job_t_s_notes.name AS note_name', 'job_t_s_notes.id AS note_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_notes.datetime AS datetime')->limit(5)->get();
            $jobGaleriesList = DB::table('user_job_t_s_galeries')->join('job_t_s_galeries', 'user_job_t_s_galeries.job_t_s_galery_id', '=', 'job_t_s_galeries.id')->join('users', 'user_job_t_s_galeries.user_id', '=', 'users.id')->where('user_job_t_s_galeries.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_galeries.deleted_at', '=', null);})->orderBy('user_job_t_s_galeries.created_at', 'desc')->select('job_t_s_galeries.name AS galery_name', 'job_t_s_galeries.id AS galery_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_galeries.datetime AS datetime')->limit(5)->get();
            $jobImagesList = DB::table('user_job_t_s_galery_images')->join('job_t_s_galery_images', 'user_job_t_s_galery_images.job_t_s_g_image_id', '=', 'job_t_s_galery_images.id')->join('users', 'user_job_t_s_galery_images.user_id', '=', 'users.id')->where('user_job_t_s_galery_images.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_galery_images.deleted_at', '=', null);})->orderBy('user_job_t_s_galery_images.created_at', 'desc')->select('job_t_s_galery_images.name AS image_name', 'job_t_s_galery_images.id AS image_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_galery_images.datetime AS datetime')->limit(5)->get();
            $jobPlaylistsList = DB::table('user_job_t_s_playlists')->join('job_t_s_playlists', 'user_job_t_s_playlists.j_t_s_p_id', '=', 'job_t_s_playlists.id')->join('users', 'user_job_t_s_playlists.user_id', '=', 'users.id')->where('user_job_t_s_playlists.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_playlists.deleted_at', '=', null);})->orderBy('user_job_t_s_playlists.created_at', 'desc')->select('job_t_s_playlists.name AS playlist_name', 'job_t_s_playlists.id AS playlist_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_playlists.datetime AS datetime')->limit(5)->get();
            $jobAudiosList = DB::table('user_job_t_s_p_audios')->join('job_t_s_p_audios', 'user_job_t_s_p_audios.j_t_s_p_a_id', '=', 'job_t_s_p_audios.id')->join('users', 'user_job_t_s_p_audios.user_id', '=', 'users.id')->where('user_job_t_s_p_audios.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_p_audios.deleted_at', '=', null);})->orderBy('user_job_t_s_p_audios.created_at', 'desc')->select('job_t_s_p_audios.name AS audio_name', 'job_t_s_p_audios.id AS audio_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_p_audios.datetime AS datetime')->limit(5)->get();
            $jobToolsList = DB::table('user_job_t_s_tools')->join('job_t_s_tools', 'user_job_t_s_tools.job_t_s_tool_id', '=', 'job_t_s_tools.id')->join('users', 'user_job_t_s_tools.user_id', '=', 'users.id')->where('user_job_t_s_tools.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_tools.deleted_at', '=', null);})->orderBy('user_job_t_s_tools.created_at', 'desc')->select('job_t_s_tools.name AS tool_name', 'job_t_s_tools.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_tools.datetime AS datetime')->limit(5)->get();
            $jobToolFilesList = DB::table('user_job_t_s_tool_files')->join('job_t_s_tool_files', 'user_job_t_s_tool_files.job_t_s_t_file_id', '=', 'job_t_s_tool_files.id')->join('users', 'user_job_t_s_tool_files.user_id', '=', 'users.id')->where('user_job_t_s_tool_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_job_t_s_tool_files.deleted_at', '=', null);})->orderBy('user_job_t_s_tool_files.created_at', 'desc')->select('job_t_s_tool_files.name AS tool_name', 'job_t_s_tool_files.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_job_t_s_tool_files.datetime AS datetime')->limit(5)->get();
    
            $projectsList = DB::table('user_projects')->join('projects', 'user_projects.project_id', '=', 'projects.id')->join('users', 'user_projects.user_id', '=', 'users.id')->where('user_projects.user_id', '=', $user_id)->where(function ($query) {$query->where('user_projects.deleted_at', '=', null);})->orderBy('user_projects.created_at', 'desc')->select('projects.name AS project_name', 'projects.id AS project_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_projects.datetime AS datetime')->limit(5)->get();
            $projectTopicsList = DB::table('user_project_topics')->join('project_topics', 'user_project_topics.project_topic_id', '=', 'project_topics.id')->join('users', 'user_project_topics.user_id', '=', 'users.id')->where('user_project_topics.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_topics.deleted_at', '=', null);})->orderBy('user_project_topics.created_at', 'desc')->select('project_topics.name AS topic_name', 'project_topics.id AS topic_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_topics.datetime AS datetime')->limit(5)->get();
            $projectSectionsList = DB::table('user_project_topic_sections')->join('project_topic_sections', 'user_project_topic_sections.project_topic_section_id', '=', 'project_topic_sections.id')->join('users', 'user_project_topic_sections.user_id', '=', 'users.id')->where('user_project_topic_sections.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_topic_sections.deleted_at', '=', null);})->orderBy('user_project_topic_sections.created_at', 'desc')->select('project_topic_sections.name AS section_name', 'project_topic_sections.id AS section_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_topic_sections.datetime AS datetime')->limit(5)->get();
            $projectFilesList = DB::table('user_project_t_s_files')->join('project_t_s_files', 'user_project_t_s_files.project_t_s_file_id', '=', 'project_t_s_files.id')->join('users', 'user_project_t_s_files.user_id', '=', 'users.id')->where('user_project_t_s_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_files.deleted_at', '=', null);})->orderBy('user_project_t_s_files.created_at', 'desc')->select('project_t_s_files.name AS file_name', 'project_t_s_files.id AS file_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_files.datetime AS datetime')->limit(5)->get();
            $projectNotesList = DB::table('user_project_t_s_notes')->join('project_t_s_notes', 'user_project_t_s_notes.project_t_s_note_id', '=', 'project_t_s_notes.id')->join('users', 'user_project_t_s_notes.user_id', '=', 'users.id')->where('user_project_t_s_notes.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_notes.deleted_at', '=', null);})->orderBy('user_project_t_s_notes.created_at', 'desc')->select('project_t_s_notes.name AS note_name', 'project_t_s_notes.id AS note_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_notes.datetime AS datetime')->limit(5)->get();
            $projectGaleriesList = DB::table('user_project_t_s_galeries')->join('project_t_s_galeries', 'user_project_t_s_galeries.project_t_s_galery_id', '=', 'project_t_s_galeries.id')->join('users', 'user_project_t_s_galeries.user_id', '=', 'users.id')->where('user_project_t_s_galeries.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_galeries.deleted_at', '=', null);})->orderBy('user_project_t_s_galeries.created_at', 'desc')->select('project_t_s_galeries.name AS galery_name', 'project_t_s_galeries.id AS galery_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_galeries.datetime AS datetime')->limit(5)->get();
            $projectImagesList = DB::table('user_project_t_s_galery_images')->join('project_t_s_galery_images', 'user_project_t_s_galery_images.project_t_s_g_image_id', '=', 'project_t_s_galery_images.id')->join('users', 'user_project_t_s_galery_images.user_id', '=', 'users.id')->where('user_project_t_s_galery_images.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_galery_images.deleted_at', '=', null);})->orderBy('user_project_t_s_galery_images.created_at', 'desc')->select('project_t_s_galery_images.name AS image_name', 'project_t_s_galery_images.id AS image_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_galery_images.datetime AS datetime')->limit(5)->get();
            $projectPlaylistsList = DB::table('user_project_t_s_playlists')->join('project_t_s_playlists', 'user_project_t_s_playlists.p_t_s_p_id', '=', 'project_t_s_playlists.id')->join('users', 'user_project_t_s_playlists.user_id', '=', 'users.id')->where('user_project_t_s_playlists.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_playlists.deleted_at', '=', null);})->orderBy('user_project_t_s_playlists.created_at', 'desc')->select('project_t_s_playlists.name AS playlist_name', 'project_t_s_playlists.id AS playlist_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_playlists.datetime AS datetime')->limit(5)->get();
            $projectAudiosList = DB::table('user_project_t_s_p_audios')->join('project_t_s_p_audios', 'user_project_t_s_p_audios.p_t_s_p_a_id', '=', 'project_t_s_p_audios.id')->join('users', 'user_project_t_s_p_audios.user_id', '=', 'users.id')->where('user_project_t_s_p_audios.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_p_audios.deleted_at', '=', null);})->orderBy('user_project_t_s_p_audios.created_at', 'desc')->select('project_t_s_p_audios.name AS audio_name', 'project_t_s_p_audios.id AS audio_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_p_audios.datetime AS datetime')->limit(5)->get();
            $projectToolsList = DB::table('user_project_t_s_tools')->join('project_t_s_tools', 'user_project_t_s_tools.project_t_s_tool_id', '=', 'project_t_s_tools.id')->join('users', 'user_project_t_s_tools.user_id', '=', 'users.id')->where('user_project_t_s_tools.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_tools.deleted_at', '=', null);})->orderBy('user_project_t_s_tools.created_at', 'desc')->select('project_t_s_tools.name AS tool_name', 'project_t_s_tools.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_tools.datetime AS datetime')->limit(5)->get();
            $projectToolFilesList = DB::table('user_project_t_s_tool_files')->join('project_t_s_tool_files', 'user_project_t_s_tool_files.project_t_s_t_file_id', '=', 'project_t_s_tool_files.id')->join('users', 'user_project_t_s_tool_files.user_id', '=', 'users.id')->where('user_project_t_s_tool_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_project_t_s_tool_files.deleted_at', '=', null);})->orderBy('user_project_t_s_tool_files.created_at', 'desc')->select('project_t_s_tool_files.name AS tool_name', 'project_t_s_tool_files.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_project_t_s_tool_files.datetime AS datetime')->limit(5)->get();
    
            $personalDatasList = DB::table('user_personal_datas')->join('personal_datas', 'user_personal_datas.personal_data_id', '=', 'personal_datas.id')->join('users', 'user_personal_datas.user_id', '=', 'users.id')->where('user_personal_datas.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_datas.deleted_at', '=', null);})->orderBy('user_personal_datas.created_at', 'desc')->select('personal_datas.name AS personal_data_name', 'personal_datas.id AS personal_data_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_datas.datetime AS datetime')->limit(5)->get();
            $personalDataTopicsList = DB::table('user_personal_data_topics')->join('personal_data_topics', 'user_personal_data_topics.personal_data_topic_id', '=', 'personal_data_topics.id')->join('users', 'user_personal_data_topics.user_id', '=', 'users.id')->where('user_personal_data_topics.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_topics.deleted_at', '=', null);})->orderBy('user_personal_data_topics.created_at', 'desc')->select('personal_data_topics.name AS topic_name', 'personal_data_topics.id AS topic_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_topics.datetime AS datetime')->limit(5)->get();
            $personalDataSectionsList = DB::table('user_personal_data_topic_sections')->join('personal_data_topic_sections', 'user_personal_data_topic_sections.personal_data_t_s_id', '=', 'personal_data_topic_sections.id')->join('users', 'user_personal_data_topic_sections.user_id', '=', 'users.id')->where('user_personal_data_topic_sections.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_topic_sections.deleted_at', '=', null);})->orderBy('user_personal_data_topic_sections.created_at', 'desc')->select('personal_data_topic_sections.name AS section_name', 'personal_data_topic_sections.id AS section_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_topic_sections.datetime AS datetime')->limit(5)->get();
            $personalDataFilesList = DB::table('user_personal_data_t_s_files')->join('personal_data_t_s_files', 'user_personal_data_t_s_files.personal_data_t_s_file_id', '=', 'personal_data_t_s_files.id')->join('users', 'user_personal_data_t_s_files.user_id', '=', 'users.id')->where('user_personal_data_t_s_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_files.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_files.created_at', 'desc')->select('personal_data_t_s_files.name AS file_name', 'personal_data_t_s_files.id AS file_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_files.datetime AS datetime')->limit(5)->get();
            $personalDataNotesList = DB::table('user_personal_data_t_s_notes')->join('personal_data_t_s_notes', 'user_personal_data_t_s_notes.personal_data_t_s_note_id', '=', 'personal_data_t_s_notes.id')->join('users', 'user_personal_data_t_s_notes.user_id', '=', 'users.id')->where('user_personal_data_t_s_notes.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_notes.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_notes.created_at', 'desc')->select('personal_data_t_s_notes.name AS note_name', 'personal_data_t_s_notes.id AS note_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_notes.datetime AS datetime')->limit(5)->get();
            $personalDataGaleriesList = DB::table('user_personal_data_t_s_galeries')->join('personal_data_t_s_galeries', 'user_personal_data_t_s_galeries.personal_data_t_s_g_id', '=', 'personal_data_t_s_galeries.id')->join('users', 'user_personal_data_t_s_galeries.user_id', '=', 'users.id')->where('user_personal_data_t_s_galeries.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_galeries.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_galeries.created_at', 'desc')->select('personal_data_t_s_galeries.name AS galery_name', 'personal_data_t_s_galeries.id AS galery_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_galeries.datetime AS datetime')->limit(5)->get();
            $personalDataImagesList = DB::table('user_personal_data_t_s_galery_images')->join('personal_data_t_s_galery_images', 'user_personal_data_t_s_galery_images.p_d_t_s_g_i_id', '=', 'personal_data_t_s_galery_images.id')->join('users', 'user_personal_data_t_s_galery_images.user_id', '=', 'users.id')->where('user_personal_data_t_s_galery_images.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_galery_images.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_galery_images.created_at', 'desc')->select('personal_data_t_s_galery_images.name AS image_name', 'personal_data_t_s_galery_images.id AS image_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_galery_images.datetime AS datetime')->limit(5)->get();
            $personalDataPlaylistsList = DB::table('user_personal_data_t_s_p')->join('personal_data_t_s_playlists', 'user_personal_data_t_s_p.p_d_t_s_p_id', '=', 'personal_data_t_s_playlists.id')->join('users', 'user_personal_data_t_s_p.user_id', '=', 'users.id')->where('user_personal_data_t_s_p.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_p.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_p.created_at', 'desc')->select('personal_data_t_s_playlists.name AS playlist_name', 'personal_data_t_s_playlists.id AS playlist_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_p.datetime AS datetime')->limit(5)->get();
            $personalDataAudiosList = DB::table('user_p_d_t_s_p_audios')->join('personal_data_t_s_p_audios', 'user_p_d_t_s_p_audios.p_d_t_s_p_a_id', '=', 'personal_data_t_s_p_audios.id')->join('users', 'user_p_d_t_s_p_audios.user_id', '=', 'users.id')->where('user_p_d_t_s_p_audios.user_id', '=', $user_id)->where(function ($query) {$query->where('user_p_d_t_s_p_audios.deleted_at', '=', null);})->orderBy('user_p_d_t_s_p_audios.created_at', 'desc')->select('personal_data_t_s_p_audios.name AS audio_name', 'personal_data_t_s_p_audios.id AS audio_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_p_d_t_s_p_audios.datetime AS datetime')->limit(5)->get();
            $personalDataToolsList = DB::table('user_personal_data_t_s_tools')->join('personal_data_t_s_tools', 'user_personal_data_t_s_tools.personal_data_t_s_tool_id', '=', 'personal_data_t_s_tools.id')->join('users', 'user_personal_data_t_s_tools.user_id', '=', 'users.id')->where('user_personal_data_t_s_tools.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_tools.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_tools.created_at', 'desc')->select('personal_data_t_s_tools.name AS tool_name', 'personal_data_t_s_tools.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_tools.datetime AS datetime')->limit(5)->get();
            $personalDataToolFilesList = DB::table('user_personal_data_t_s_tool_files')->join('personal_data_t_s_tool_files', 'user_personal_data_t_s_tool_files.personal_d_t_s_t_f_id', '=', 'personal_data_t_s_tool_files.id')->join('users', 'user_personal_data_t_s_tool_files.user_id', '=', 'users.id')->where('user_personal_data_t_s_tool_files.user_id', '=', $user_id)->where(function ($query) {$query->where('user_personal_data_t_s_tool_files.deleted_at', '=', null);})->orderBy('user_personal_data_t_s_tool_files.created_at', 'desc')->select('personal_data_t_s_tool_files.name AS tool_name', 'personal_data_t_s_tool_files.id AS tool_id', 'users.name AS user_name', 'users.id AS user_id', 'users.email AS email', 'user_personal_data_t_s_tool_files.datetime AS datetime')->limit(5)->get();
    
            $calendarEventsList = DB::table('user_calendar_events')->join('calendar_events', 'user_calendar_events.calendar_event_id', '=', 'calendar_events.id')->join('users', 'calendar_events.user_id', '=', 'users.id')->where('user_calendar_events.user_id', '=', $user_id)->where(function ($query) {$query->where('user_calendar_events.deleted_at', '=', null);})->orderBy('user_calendar_events.created_at', 'desc')->select('calendar_events.name', 'calendar_events.id', 'calendar_events.color', 'calendar_events.start_date')->orderBy('user_calendar_events.created_at', 'desc')->limit(10)->get();
                
            return view('sharedFile')
                ->with('colleges', $colleges)
                ->with('collegeTopics', $collegeTopics)
                ->with('collegeSections', $collegeSections)
                ->with('collegeFiles', $collegeFiles)
                ->with('collegeNotes', $collegeNotes)
                ->with('collegeGaleries', $collegeGaleries)
                ->with('collegeImages', $collegeImages)
                ->with('collegePlaylists', $collegePlaylists)
                ->with('collegeAudios', $collegeAudios)
                ->with('collegeTools', $collegeTools)
                ->with('collegeToolFiles', $collegeToolFiles)
                ->with('jobs', $jobs)
                ->with('jobTopics', $jobTopics)
                ->with('jobSections', $jobSections)
                ->with('jobFiles', $jobFiles)
                ->with('jobNotes', $jobNotes)
                ->with('jobGaleries', $jobGaleries)
                ->with('jobImages', $jobImages)
                ->with('jobPlaylists', $jobPlaylists)
                ->with('jobAudios', $jobAudios)
                ->with('jobTools', $jobTools)
                ->with('jobToolFiles', $jobToolFiles)
                ->with('projects', $projects)
                ->with('projectTopics', $projectTopics)
                ->with('projectSections', $projectSections)
                ->with('projectFiles', $projectFiles)
                ->with('projectNotes', $projectNotes)
                ->with('projectGaleries', $projectGaleries)
                ->with('projectImages', $projectImages)
                ->with('projectPlaylists', $projectPlaylists)
                ->with('projectAudios', $projectAudios)
                ->with('projectTools', $projectTools)
                ->with('projectToolFiles', $projectToolFiles)
                ->with('personalDatas', $personalDatas)
                ->with('personalDataTopics', $personalDataTopics)
                ->with('personalDataSections', $personalDataSections)
                ->with('personalDataFiles', $personalDataFiles)
                ->with('personalDataNotes', $personalDataNotes)
                ->with('personalDataGaleries', $personalDataGaleries)
                ->with('personalDataImages', $personalDataImages)
                ->with('personalDataPlaylists', $personalDataPlaylists)
                ->with('personalDataAudios', $personalDataAudios)
                ->with('personalDataTools', $personalDataTools)
                ->with('personalDataToolFiles', $personalDataToolFiles)
                ->with('college_p', $college_p)
                ->with('college_topic_p', $college_topic_p)
                ->with('college_section_p', $college_section_p)
                ->with('college_file_p', $college_file_p)
                ->with('college_note_p', $college_note_p)
                ->with('college_galery_p', $college_galery_p)
                ->with('college_image_p', $college_image_p)
                ->with('college_playlist_p', $college_playlist_p)
                ->with('college_audio_p', $college_audio_p)
                ->with('college_tool_p', $college_tool_p)
                ->with('college_tool_file_p', $college_tool_file_p)
                ->with('job_p', $job_p)
                ->with('job_topic_p', $job_topic_p)
                ->with('job_section_p', $job_section_p)
                ->with('job_file_p', $job_file_p)
                ->with('job_note_p', $job_note_p)
                ->with('job_galery_p', $job_galery_p)
                ->with('job_image_p', $job_image_p)
                ->with('job_playlist_p', $job_playlist_p)
                ->with('job_audio_p', $job_audio_p)
                ->with('job_tool_p', $job_tool_p)
                ->with('job_tool_file_p', $job_tool_file_p)
                ->with('project_p', $project_p)
                ->with('project_topic_p', $project_topic_p)
                ->with('project_section_p', $project_section_p)
                ->with('project_file_p', $project_file_p)
                ->with('project_note_p', $project_note_p)
                ->with('project_galery_p', $project_galery_p)
                ->with('project_image_p', $project_image_p)
                ->with('project_playlist_p', $project_playlist_p)
                ->with('project_audio_p', $project_audio_p)
                ->with('project_tool_p', $project_tool_p)
                ->with('project_tool_file_p', $project_tool_file_p)
                ->with('personal_data_p', $personal_data_p)
                ->with('personal_data_topic_p', $personal_data_topic_p)
                ->with('personal_data_section_p', $personal_data_section_p)
                ->with('personal_data_file_p', $personal_data_file_p)
                ->with('personal_data_note_p', $personal_data_note_p)
                ->with('personal_data_galery_p', $personal_data_galery_p)
                ->with('personal_data_image_p', $personal_data_image_p)
                ->with('personal_data_playlist_p', $personal_data_playlist_p)
                ->with('personal_data_audio_p', $personal_data_audio_p)
                ->with('personal_data_tool_p', $personal_data_tool_p)
                ->with('personal_data_tool_file_p', $personal_data_tool_file_p)
                ->with('calendarEvents', $calendarEvents)
                ->with('collegesList', $colleges)
                ->with('collegeTopicsList', $collegeTopics)
                ->with('collegeSectionsList', $collegeSections)
                ->with('collegeFilesList', $collegeFiles)
                ->with('collegeNotesList', $collegeNotes)
                ->with('collegeGaleriesList', $collegeGaleries)
                ->with('collegeImagesList', $collegeImages)
                ->with('collegePlaylistsList', $collegePlaylists)
                ->with('collegeAudiosList', $collegeAudios)
                ->with('collegeToolsList', $collegeTools)
                ->with('collegeToolFilesList', $collegeToolFiles)
                ->with('jobsList', $jobs)
                ->with('jobTopicsList', $jobTopics)
                ->with('jobSectionsList', $jobSections)
                ->with('jobFilesList', $jobFiles)
                ->with('jobNotesList', $jobNotes)
                ->with('jobGaleriesList', $jobGaleries)
                ->with('jobImagesList', $jobImages)
                ->with('jobPlaylistsList', $jobPlaylists)
                ->with('jobAudiosList', $jobAudios)
                ->with('jobToolsList', $jobTools)
                ->with('jobToolFilesList', $jobToolFiles)
                ->with('projectsList', $projects)
                ->with('projectTopicsList', $projectTopics)
                ->with('projectSectionsList', $projectSections)
                ->with('projectFilesList', $projectFiles)
                ->with('projectNotesList', $projectNotes)
                ->with('projectGaleriesList', $projectGaleries)
                ->with('projectImagesList', $projectImages)
                ->with('projectPlaylistsList', $projectPlaylists)
                ->with('projectAudiosList', $projectAudios)
                ->with('projectToolsList', $projectTools)
                ->with('projectToolFilesList', $projectToolFiles)
                ->with('personalDatasList', $personalDatas)
                ->with('personalDataTopicsList', $personalDataTopics)
                ->with('personalDataSectionsList', $personalDataSections)
                ->with('personalDataFilesList', $personalDataFiles)
                ->with('personalDataNotesList', $personalDataNotes)
                ->with('personalDataGaleriesList', $personalDataGaleries)
                ->with('personalDataImagesList', $personalDataImages)
                ->with('personalDataPlaylistsList', $personalDataPlaylists)
                ->with('personalDataAudiosList', $personalDataAudios)
                ->with('personalDataToolsList', $personalDataTools)
                ->with('personalDataToolFilesList', $personalDataToolFiles)
                ->with('calendarEventsList', $calendarEventsList);
        }
        
        else
        {
            return view('deniedAccess');
        }
    }

    public function create()
    {
        
    }

    public function store(Request $request)
    {
        
    }

    public function show($id)
    {
        
    }

    public function edit($id)
    {

    }

    public function update(Request $request, $id)
    {
    
    }

    public function destroy($id)
    {
        
    }
}